services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  Simply\Mvc\:
    resource: '../src/'
    exclude:
      - '../src/Application.php'
      - '../src/Routing/Route.php'
      - '../src/Attribute/*'
      - '../src/Controller/ControllerResolver.php'

  Simply\Mvc\Hook\TemplateInclude:
    tags: ['container.service_subscriber']

